"""
Effective Compute Access (ECA) computation.

ECA formula:
    ECA(c, b) = ECA_E(c, b) × α(availability) × δ(legal_scenario)

Where:
    ECA_E        = floor(budget / (price × H / norm)) × peak_TFLOP/s
    α            = availability modifier (GA=1.0, Limited=0.5,
                   Waitlisted=0.1, Unavailable=0.0)
    δ            = legal scenario multiplier
                   (Scenario A = 1.0, B_low/mid/high = 0.3/0.5/0.7,
                    Scenario C = 0.0)

The module computes TWO ECA variants per record:

  * eca_scenario_*           — discrete: floor() the number of whole runs,
                               then multiply by peak TFLOP/s. This matches
                               "how many complete training runs can you
                               execute?" and is useful for practical
                               governance/capacity planning.
  * eca_continuous_scenario_*— continuous: uses runs_per_budget verbatim
                               (no floor). This reveals the smooth
                               purchasing-power gradient that the discrete
                               metric hides (e.g. Germany vs. Japan at the
                               same chip count).

A nominal helper (`eca_nominal_tflops`) is also emitted for the
pre-PPP/availability/legal baseline, used by the compounding-gap chart.
"""

import argparse
import csv
import math
from dataclasses import dataclass, asdict, fields
from pathlib import Path
from typing import Optional


@dataclass
class ECAResult:
    """ECA computation result for one AAR record under all scenarios."""

    # From AAR
    country_name: str
    country_iso: str
    provider: str
    region_code: str
    gpu_class: str

    # Input parameters
    budget_usd: float
    reference_hours: int
    normalization_method: str  # "ppp", "gdp_per_capita", "rd_per_researcher"

    # Physical layer — availability modifier α ∈ {1.0, 0.5, 0.1, 0.0}
    availability_class: str
    alpha_availability: float

    # Economic layer — detailed breakdown
    on_demand_usd_per_gpu_hr: float
    nominal_run_cost_usd: float  # price × H (cost of 1 GPU for H hours)
    ppp_factor: float
    normalization_value: float  # The actual normalization denominator used
    adjusted_run_cost_usd: float  # nominal × normalization adjustment
    runs_per_budget: float  # How many H-hour runs the budget buys
    affordable_chips: int  # floor of runs_per_budget
    eca_economic_tflops: float  # affordable_chips × peak_TFLOP/s
    # Pre-normalisation baseline used by the compounding-gap chart: what the
    # budget buys at the nominal USD price, ignoring PPP/availability/legal.
    eca_nominal_tflops: float

    # Legal layer
    bis_tier: int

    # Composite ECA under each scenario (discrete; uses floor)
    eca_scenario_a: float  # Unconstrained (δ=1.0)
    eca_scenario_b_low: float  # Partially constrained (δ=0.3)
    eca_scenario_b_mid: float  # Partially constrained (δ=0.5)
    eca_scenario_b_high: float  # Partially constrained (δ=0.7)
    eca_scenario_c: float  # Prohibited (δ=0.0)

    # Continuous ECA (no floor) — exposes purchasing-power gradient.
    eca_continuous_tflops: float  # runs_per_budget × peak_TFLOP/s
    eca_continuous_scenario_a: float
    eca_continuous_scenario_b_mid: float

    # Ratios (relative to USA baseline for same provider+GPU)
    ratio_to_usa_scenario_a: Optional[float] = None

    # Descriptive pass-through fields (from AAR-Core) — do not affect ECA.
    # They are emitted in the CSV so downstream visualizations can annotate
    # compounding constraints (e.g. non-local routing × sovereignty).
    is_local_region: bool = True
    data_sovereignty_class: str = "none"


def load_aar_csv(path: Path) -> list[dict]:
    """Load AAR records from CSV."""
    with open(path) as f:
        reader = csv.DictReader(f)
        records = []
        for row in reader:
            row["peak_tflops_bf16_dense"] = float(row["peak_tflops_bf16_dense"])
            row["on_demand_usd_per_gpu_hr"] = float(row["on_demand_usd_per_gpu_hr"])
            row["ppp_factor"] = float(row["ppp_factor"])
            row["gdp_per_capita_usd"] = float(row["gdp_per_capita_usd"])
            row["availability_score"] = float(row["availability_score"])
            row["bis_tier"] = int(row["bis_tier"])
            rd = row.get("rd_spend_per_researcher_usd")
            row["rd_spend_per_researcher_usd"] = float(rd) if rd and rd != "None" else None
            # Locality fields (added in README_04) — optional for backwards
            # compatibility with AAR CSVs generated by older versions.
            if "is_local_region" in row:
                row["is_local_region"] = str(row["is_local_region"]).strip().lower() in ("true", "1", "yes")
            # Data sovereignty (README_06) — optional pass-through.
            if "data_sovereignty_class" not in row or row["data_sovereignty_class"] in (None, "", "None"):
                row["data_sovereignty_class"] = "none"
            records.append(row)
    return records


def compute_normalization_value(
    record: dict,
    method: str,
    usa_reference: dict,
) -> float:
    """Compute the normalization adjustment factor.

    Returns a multiplier applied to nominal cost to get adjusted cost.
    Lower value = less purchasing power = more expensive in real terms.

    Methods:
        ppp: Uses PPP price-level ratio directly (USA=1.0 baseline).
        gdp_per_capita: Uses GDP per capita ratio (country/USA).
        rd_per_researcher: Uses R&D spend per researcher ratio (country/USA).
    """
    if method == "ppp":
        return record["ppp_factor"]

    elif method == "gdp_per_capita":
        usa_gdp = usa_reference["gdp_per_capita_usd"]
        country_gdp = record["gdp_per_capita_usd"]
        return country_gdp / usa_gdp

    elif method == "rd_per_researcher":
        rd = record.get("rd_spend_per_researcher_usd")
        usa_rd = usa_reference.get("rd_spend_per_researcher_usd")
        if rd and usa_rd and float(usa_rd) > 0:
            return float(rd) / float(usa_rd)
        else:
            return record["ppp_factor"]

    else:
        raise ValueError(f"Unknown normalization method: {method}")


def _legal_deltas(bis_tier: int) -> tuple[float, float, float, float, float]:
    """Return (δ_A, δ_B_low, δ_B_mid, δ_B_high, δ_C) for a BIS tier."""
    if bis_tier == 1:
        return 1.0, 1.0, 1.0, 1.0, 1.0
    if bis_tier == 2:
        return 1.0, 0.3, 0.5, 0.7, 0.0
    # Tier 3 — prohibited under all scenarios.
    return 0.0, 0.0, 0.0, 0.0, 0.0


def compute_eca(
    records: list[dict],
    budget_usd: float = 10_000,
    reference_hours: int = 720,
    normalization_method: str = "ppp",
) -> list[ECAResult]:
    """Compute ECA for all AAR records."""

    usa_records = {
        (r["provider"], r["gpu_class"]): r
        for r in records
        if r["country_iso"] == "USA"
    }

    results: list[ECAResult] = []

    for rec in records:
        price = rec["on_demand_usd_per_gpu_hr"]
        peak_tflops = rec["peak_tflops_bf16_dense"]
        alpha = rec["availability_score"]  # availability modifier
        bis_tier = rec["bis_tier"]

        usa_ref = usa_records.get((rec["provider"], rec["gpu_class"]))
        if usa_ref is None:
            continue

        nominal_run_cost = price * reference_hours
        norm_value = compute_normalization_value(rec, normalization_method, usa_ref)
        adjusted_run_cost = nominal_run_cost / norm_value

        runs = budget_usd / adjusted_run_cost
        affordable_chips = math.floor(runs)
        eca_e = affordable_chips * peak_tflops

        # Pre-PPP/α/δ baseline: chips affordable at nominal USD price.
        nominal_chips = math.floor(budget_usd / nominal_run_cost) if nominal_run_cost > 0 else 0
        eca_nominal = nominal_chips * peak_tflops

        # Continuous ECA uses the raw `runs` (no floor) to preserve gradient.
        eca_continuous_e = runs * peak_tflops

        # Legal deltas (Scenarios A, B_low, B_mid, B_high, C).
        delta_a, delta_b_low, delta_b_mid, delta_b_high, delta_c = _legal_deltas(bis_tier)

        # Composite ECA = ECA_E × α × δ
        eca_base = eca_e * alpha
        eca_a = eca_base * delta_a
        eca_b_low = eca_base * delta_b_low
        eca_b_mid = eca_base * delta_b_mid
        eca_b_high = eca_base * delta_b_high
        eca_c = eca_base * delta_c

        # Continuous counterparts.
        eca_cont_base = eca_continuous_e * alpha
        eca_cont_a = eca_cont_base * delta_a
        eca_cont_b_mid = eca_cont_base * delta_b_mid

        # Ratio to USA baseline for same (provider, GPU).
        ratio: Optional[float] = None
        if usa_ref:
            usa_norm = compute_normalization_value(usa_ref, normalization_method, usa_ref)
            usa_adj = (usa_ref["on_demand_usd_per_gpu_hr"] * reference_hours) / usa_norm
            usa_chips = math.floor(budget_usd / usa_adj)
            usa_eca = usa_chips * peak_tflops  # USA is Tier 1, GA → α=1, δ=1.
            ratio = eca_a / usa_eca if usa_eca > 0 else None

        result = ECAResult(
            country_name=rec["country_name"],
            country_iso=rec["country_iso"],
            provider=rec["provider"],
            region_code=rec["region_code"],
            gpu_class=rec["gpu_class"],
            budget_usd=budget_usd,
            reference_hours=reference_hours,
            normalization_method=normalization_method,
            availability_class=rec["availability_class"],
            alpha_availability=alpha,
            on_demand_usd_per_gpu_hr=price,
            nominal_run_cost_usd=round(nominal_run_cost, 2),
            ppp_factor=rec["ppp_factor"],
            normalization_value=round(norm_value, 4),
            adjusted_run_cost_usd=round(adjusted_run_cost, 2),
            runs_per_budget=round(runs, 3),
            affordable_chips=affordable_chips,
            eca_economic_tflops=round(eca_e, 1),
            eca_nominal_tflops=round(eca_nominal, 1),
            bis_tier=bis_tier,
            eca_scenario_a=round(eca_a, 1),
            eca_scenario_b_low=round(eca_b_low, 1),
            eca_scenario_b_mid=round(eca_b_mid, 1),
            eca_scenario_b_high=round(eca_b_high, 1),
            eca_scenario_c=round(eca_c, 1),
            eca_continuous_tflops=round(eca_continuous_e, 1),
            eca_continuous_scenario_a=round(eca_cont_a, 1),
            eca_continuous_scenario_b_mid=round(eca_cont_b_mid, 1),
            ratio_to_usa_scenario_a=round(ratio, 3) if ratio is not None else None,
            is_local_region=bool(rec.get("is_local_region", True)),
            data_sovereignty_class=rec.get("data_sovereignty_class", "none"),
        )
        results.append(result)

    return results


def compute_eca_budget_sweep(
    records: list[dict],
    budgets: list[float] = (5_000, 10_000, 25_000, 50_000, 100_000),
    reference_hours: int = 720,
    normalization_method: str = "ppp",
) -> list[ECAResult]:
    """Run ECA for multiple budget levels.

    Returns results for every (country × provider × GPU × budget) combination.
    Consumers can group by budget to produce multi-budget charts.
    """
    all_results: list[ECAResult] = []
    for budget in budgets:
        results = compute_eca(
            records,
            budget_usd=float(budget),
            reference_hours=reference_hours,
            normalization_method=normalization_method,
        )
        all_results.extend(results)
    return all_results


def results_to_csv(results: list[ECAResult], output_path: Path) -> None:
    """Write ECA results to CSV."""
    if not results:
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [f.name for f in fields(ECAResult)]
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            writer.writerow(asdict(r))


def print_summary(results: list[ECAResult]) -> None:
    """Print a human-readable summary table."""
    print("\n" + "=" * 96)
    print("ECA SUMMARY — Scenario A (Unconstrained)")
    print("=" * 96)
    print(
        f"{'Country':<20} {'GPU':<12} {'Provider':<6} {'Runs/budget':<12} "
        f"{'ECA (TFLOP/s)':<15} {'Cont. ECA':<12} {'vs USA':<8}"
    )
    print("-" * 96)

    for r in sorted(results, key=lambda x: (x.gpu_class, -x.eca_scenario_a)):
        ratio_str = f"{r.ratio_to_usa_scenario_a:.2f}x" if r.ratio_to_usa_scenario_a else "N/A"
        print(
            f"{r.country_name:<20} {r.gpu_class:<12} {r.provider:<6} "
            f"{r.runs_per_budget:<12.2f} {r.eca_scenario_a:<15.1f} "
            f"{r.eca_continuous_scenario_a:<12.1f} {ratio_str:<8}"
        )

    print("\n" + "=" * 96)
    print("COMPOUNDING ANALYSIS — How legal scenarios affect Tier 2 countries")
    print("=" * 96)
    tier2 = [r for r in results if r.bis_tier == 2]
    for r in sorted(tier2, key=lambda x: (x.gpu_class, x.country_name)):
        print(
            f"{r.country_name:<20} {r.gpu_class:<12} "
            f"A={r.eca_scenario_a:<10.1f} B(mid)={r.eca_scenario_b_mid:<10.1f} "
            f"C={r.eca_scenario_c:<10.1f}"
        )


def _parse_budgets(raw: str) -> list[float]:
    return [float(x.strip()) for x in raw.split(",") if x.strip()]


def main():
    parser = argparse.ArgumentParser(description="Compute Effective Compute Access")
    parser.add_argument("--aar", type=Path, default=Path("outputs/tables/aar_records.csv"))
    parser.add_argument("--budget", type=float, default=10_000,
                        help="Single budget in USD (used when --budgets is not provided)")
    parser.add_argument("--budgets", type=str, default=None,
                        help="Comma-separated list of budgets (e.g. '5000,10000,25000,50000'). "
                             "Triggers multi-budget sweep output.")
    parser.add_argument("--hours", type=int, default=720)
    parser.add_argument("--normalization", default="ppp",
                        choices=["ppp", "gdp_per_capita", "rd_per_researcher"])
    parser.add_argument("--output", type=Path, default=Path("outputs/tables/eca_results.csv"))
    parser.add_argument("--sweep-output", type=Path,
                        default=Path("outputs/tables/eca_budget_sweep.csv"),
                        help="Where to write the budget sweep CSV when --budgets is set.")
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)

    records = load_aar_csv(args.aar)
    print(f"Loaded {len(records)} AAR records")

    # Always produce the single-budget output.
    single_results = compute_eca(
        records,
        budget_usd=args.budget,
        reference_hours=args.hours,
        normalization_method=args.normalization,
    )
    results_to_csv(single_results, args.output)
    print(f"Written {len(single_results)} ECA results to {args.output}")
    print_summary(single_results)

    # Optional budget sweep.
    if args.budgets:
        budgets = _parse_budgets(args.budgets)
        sweep = compute_eca_budget_sweep(
            records,
            budgets=budgets,
            reference_hours=args.hours,
            normalization_method=args.normalization,
        )
        results_to_csv(sweep, args.sweep_output)
        print(
            f"\nWritten {len(sweep)} budget-sweep results "
            f"({len(budgets)} budgets × {len(sweep) // max(len(budgets), 1)} records) "
            f"to {args.sweep_output}"
        )


if __name__ == "__main__":
    main()
